### ISSUE TITLE
Attribute 'setup_version' is missing for module 'Ashsmith_HelloWorld'.

### ISSUE THREAD

**Issue by osmansorkar** [ashsmith/magento2-controller-module#1]
Attribute 'setup_version' is missing for module 'Ashsmith_HelloWorld'.

**Comment by tungmpo** [comment]
I have also same problem

**Comment by robjmills** [comment]
you need to add a setup_version property to your module.xml, e.g.

```
<module name="Ashsmith_HelloWorld" schema_version="0.0.1" setup_version="0.0.1" />
```

**Comment by markoshust** [comment]
This should be amended in the Fundamentals of Magento 2 Development training class. I just stumbled on this going through the training session, and wasn't sure who to notify.
