### ISSUE TITLE
Unknown database 'magento' when try to upgrade DB using bin/magento setup:upgrade command

### ISSUE THREAD

**Issue by DRAJI** [ashsmith/magento2-controller-module#3]
After install 'Ashsmith_HelloWorld' , site gets down. And got an error like 

"Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. 
The following modules are outdated:
Ashsmith_HelloWorld schema: current version - none, required version - 1.0.0
Ashsmith_HelloWorld data: current version - none, required version - 1.0.0";i:1;s:1015:"#0 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#1 /opt/lampp/htdocs/projects/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#2 /opt/lampp/htdocs/projects/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#3 /opt/lampp/htdocs/projects/magento2/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /opt/lampp/htdocs/projects/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(257): Magento\Framework\App\Http->launch()
#5 /opt/lampp/htdocs/projects/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#6 {main}";s:3:"url";s:120:"/projects/magento2/admin/admin/system_config/index/key/87385a5cb4a00855f584a6d82d68f5a7c0b358e44ba7c32c1b19fc6cc15fdadf/";s:11:"script_name";s:28:"/projects/magento2/index.php";}

But when i try to upgrade DB "bin/magento setup:upgrade" , i got "unknown database" error in terminal.

Cache cleared successfully
File system cleanup:
/opt/lampp/htdocs/projects/magento2/var/generation/Magento
Updating modules:  
  [Zend_Db_Adapter_Exception]  
  SQLSTATE[42000] [1049] Unknown database 'magento'                                                            

  [PDOException]  
  SQLSTATE[42000] [1049] Unknown database 'magento'  
setup:upgrade [--magento-init-params="..."]

Thanks

**Comment by ashsmith** [comment]
From the command line you need to run `bin/magento setup:upgrade` from the root of your magento 2 install.
